# The URL the site will be built for
base_url = "https://adilettante.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "simple-dev-blog"

title = "a dilettante developer"
description = "Unrefined opinions on engineering & software."

generate_feed = true

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

[extra]

nav = [
  { name = "About", path = "/about/" },
  { name = "Projects", path = "/projects/" },
  { name = "Blog", path = "/blog/" },
]

katex_enable = true
katex_auto_render = true


latest_text = "Latest post:"

icon = "icon.png"
profile_small = "icon.png"
profile_large = "profile.jpg"

accent = "#D20048"
accent_light = "#eee"

author = "Aevyrie Roessler"

footer_about = """
© 2021 Aevyrie Roessler ~ [About](/about/) ~ [Github](https://www.github.com/aevyrie) ~ [LinkedIn](https://www.linkedin.com/in/aevyrie/)
"""

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""
